/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer { 'name' : string, 'mobile' : string }
export interface Invoice {
  'customerName' : string,
  'createdAt' : bigint,
  'invoiceNo' : string,
  'grandTotal' : bigint,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem {
  'qty' : bigint,
  'itemTotal' : bigint,
  'itemName' : string,
  'price' : bigint,
}
export interface Product { 'name' : string, 'price' : bigint }
export interface Stats { 'totalRevenue' : bigint, 'totalInvoices' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[string, string], undefined>,
  'createInvoice' : ActorMethod<
    [string, Array<InvoiceItem>, bigint, string, bigint],
    undefined
  >,
  'createProduct' : ActorMethod<[string, bigint], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getProduct' : ActorMethod<[string], Product>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];