/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemTotal' : IDL.Nat,
  'itemName' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Customer = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
export const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const Stats = IDL.Record({
  'totalRevenue' : IDL.Nat,
  'totalInvoices' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'invoiceNo' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'items' : IDL.Vec(InvoiceItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Vec(InvoiceItem), IDL.Nat, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'createProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemTotal' : IDL.Nat,
    'itemName' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Customer = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
  const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const Stats = IDL.Record({
    'totalRevenue' : IDL.Nat,
    'totalInvoices' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'invoiceNo' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'items' : IDL.Vec(InvoiceItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Vec(InvoiceItem), IDL.Nat, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'createProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };